### ISSUE TITLE
Update CI to use environment variables while building react app

### ISSUE THREAD

**Issue by jaspreet57** [pesto-students/batch-8-NuSlack#64]
In react build process, either set environment variables, or write them in .env file in project root.

Env variable required for now:
SERVER_BASE_URL=url-of-backend-server

**Comment by jaspreet57** [comment]
@abhi18av would you be working on this?
or shall I pick up.
we just need it asap.

**Comment by abhi18av** [comment]
Oh, this just needs to be done on the `CIrcleCI` config and let's try not to add an `.env` file.

**Comment by jaspreet57** [comment]
yes cool, I am not saying to add `.env` file, it is just for local environment.
You can set environment variables in `CircleCi` setup also.
So if you are going to work on it please assign it to yourself

**Comment by abhi18av** [comment]
Na, it's cool. I have the wonderful `context` PR to play with :)

**Comment by jaspreet57** [comment]
Ok good

**Comment by jaspreet57** [comment]
Closing, as it is done in `CircleCi` configuration.
